### ISSUE TITLE
copied curl commands contains backslash

### ISSUE THREAD

**Issue by MehrCurry** [iteratec/gitlab-sanity-cli#2]
Hi,

when i copy the curl commands from the README and paste them (MacOS, zsh) they contain backslashed around the OS variable and the variable is not resolved.

```
curl -L -O https://github.com/iteratec/gitlab-sanity-cli/releases/latest/download/gitlab-sanity-cli.$\{OS\}.amd64.tar.gz
curl -L -O https://github.com/iteratec/gitlab-sanity-cli/releases/latest/download/gitlab-sanity-cli.$\{OS\}.amd64.tar.gz.sha256
```

**Comment by cd-at-iteratec** [comment]
Hi @MehrCurry ,

Hmm, that looks strange. Where does the escape characters comes in ?
I tried on my terminal emulators with zsh and bash without any issue.

Maybe you can provide us a screenshot ?

Best,

CD.
